// <auto-generated />
using System;
using BandAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BandAPI.Migrations
{
    [DbContext(typeof(BandAlbumContext))]
    partial class BandAlbumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BandAPI.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa1700a6-f6af-11ea-adc1-0242ac120002"),
                            BandId = new Guid("1548d4d6-f6af-11ea-adc1-0242ac120002"),
                            Description = "One of the best ever",
                            Title = "Master of Puppets"
                        },
                        new
                        {
                            Id = new Guid("aa17043e-f6af-11ea-adc1-0242ac120002"),
                            BandId = new Guid("1548d71a-f6af-11ea-adc1-0242ac120002"),
                            Description = "One of the best ever",
                            Title = "GunsNRoses Album"
                        },
                        new
                        {
                            Id = new Guid("aa170736-f6af-11ea-adc1-0242ac120002"),
                            BandId = new Guid("1548d81e-f6af-11ea-adc1-0242ac120002"),
                            Description = "One of the best ever",
                            Title = "Abba Album"
                        },
                        new
                        {
                            Id = new Guid("aa170844-f6af-11ea-adc1-0242ac120002"),
                            BandId = new Guid("1548d8f0-f6af-11ea-adc1-0242ac120002"),
                            Description = "One of the best ever",
                            Title = "Oasis Album"
                        });
                });

            modelBuilder.Entity("BandAPI.Entities.Band", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Founded")
                        .HasColumnType("datetime2");

                    b.Property<string>("MainGenre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Bands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1548d4d6-f6af-11ea-adc1-0242ac120002"),
                            Founded = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Heavy Metal",
                            Name = "Metallica"
                        },
                        new
                        {
                            Id = new Guid("1548d71a-f6af-11ea-adc1-0242ac120002"),
                            Founded = new DateTime(1985, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Rock",
                            Name = "Guns N Roses"
                        },
                        new
                        {
                            Id = new Guid("1548d81e-f6af-11ea-adc1-0242ac120002"),
                            Founded = new DateTime(1965, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Desco",
                            Name = "ABBA"
                        },
                        new
                        {
                            Id = new Guid("1548d8f0-f6af-11ea-adc1-0242ac120002"),
                            Founded = new DateTime(1991, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Heavy Metal",
                            Name = "Oasis"
                        });
                });

            modelBuilder.Entity("BandAPI.Entities.Album", b =>
                {
                    b.HasOne("BandAPI.Entities.Band", "Band")
                        .WithMany("Albums")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
